"""add user_activations table

Revision ID: 07fff94d0a0b
Revises: 25feb4ca40e6
Create Date: 2016-09-22 18:49:01.485685

"""

# revision identifiers, used by Alembic.
revision = '07fff94d0a0b'
down_revision = '25feb4ca40e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activation_id'], ['activations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'activation_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activations')
    ### end Alembic commands ###
