"""add vb_class y_gre_class to activations

Revision ID: 319d440654d2
Revises: 8b4705e1aa57
Create Date: 2016-07-18 19:43:09.252013

"""

# revision identifiers, used by Alembic.
revision = '319d440654d2'
down_revision = '8b4705e1aa57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activations', sa.Column('vb_class', sa.String(length=64), nullable=True))
    op.add_column('activations', sa.Column('y_gre_class', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activations', 'y_gre_class')
    op.drop_column('activations', 'vb_class')
    ### end Alembic commands ###
