"""add ipad_contents_json table

Revision ID: 4d67d36233f1
Revises: 16cb6a4b2bdb
Create Date: 2016-10-21 17:11:18.616816

"""

# revision identifiers, used by Alembic.
revision = '4d67d36233f1'
down_revision = '16cb6a4b2bdb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipad_contents_json',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json_string', sa.UnicodeText(), nullable=True),
    sa.Column('out_of_date', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipad_contents_json')
    ### end Alembic commands ###
