"""add index to ipad_contents

Revision ID: 668e845b5048
Revises: 07fff94d0a0b
Create Date: 2016-10-01 22:22:00.426766

"""

# revision identifiers, used by Alembic.
revision = '668e845b5048'
down_revision = '07fff94d0a0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ipad_contents_ipad_id'), 'ipad_contents', ['ipad_id'], unique=False)
    op.create_index(op.f('ix_ipad_contents_lesson_id'), 'ipad_contents', ['lesson_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipad_contents_lesson_id'), table_name='ipad_contents')
    op.drop_index(op.f('ix_ipad_contents_ipad_id'), table_name='ipad_contents')
    ### end Alembic commands ###
