"""add user_announcements table

Revision ID: ad85e8d36c5e
Revises: 5ba27cd02152
Create Date: 2016-11-08 02:33:09.225535

"""

# revision identifiers, used by Alembic.
revision = 'ad85e8d36c5e'
down_revision = '5ba27cd02152'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_announcements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'announcement_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_announcements')
    ### end Alembic commands ###
